name: kmmi_unila
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  provider: ^5.0.0
  flutter_colorpicker: ^0.4.0
  intl: ^0.17.0
  uuid: ^3.0.4
  shared_preferences: ^2.0.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/assets/author_katz.jpeg
      - assets/images/assets/mag1.png
      - assets/images/assets/mag2.png
      - assets/images/assets/mag5.png
      - assets/images/profile_pics/person_cesare.jpeg
      - assets/images/profile_pics/person_crispy.png
      - assets/images/profile_pics/person_joe.jpeg
      - assets/images/profile_pics/person_katz.jpeg
      - assets/images/profile_pics/person_kelvin.jpg
      - assets/images/profile_pics/person_kevin.jpeg
      - assets/images/profile_pics/person_manda.png
      - assets/images/profile_pics/person_ray.jpeg
      - assets/images/profile_pics/person_sandra.jpeg
      - assets/images/profile_pics/person_stef.jpeg
      - assets/images/profile_pics/person_tiffani.jpeg
      - assets/images/magazine_pics/card_bread.jpg
      - assets/images/magazine_pics/card_carrot.png
      - assets/images/magazine_pics/card_salad.png
      - assets/images/magazine_pics/card_smoothie.png
      - assets/images/magazine_pics/mag1.png
      - assets/images/magazine_pics/mag2.png
      - assets/images/magazine_pics/mag3.png
      - assets/images/magazine_pics/mag4.png
      - assets/images/magazine_pics/mag5.png
      - assets/images/webinar_pics/augmentasi.png
      - assets/images/webinar_pics/cnn pred.png
      - assets/images/webinar_pics/nlp.png
      - assets/images/webinar_pics/process image.png
      - assets/images/webinar_pics/segmentasi.png
      - assets/images/webinar_pics/tensorflow.png
      - assets/images/webinar_pics/internweb.png
      - assets/images/webinar_pics/opencv.png
      - assets/images/webinar_pics/tfheader.png
      - assets/sample_data/sample_explore_recipes.json
      - assets/sample_data/sample_friends_feed.json
      - assets/sample_data/sample_recipes.json
      - assets/images/fooderlich_assets/empty_list.png


  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          style: italic
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          style: italic  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
